### ISSUE TITLE
How to open config dialog?

### ISSUE THREAD

**Issue by octoshrimpy** [alex1701c/TmuxRunner#1]
The readme mentions it, but does not specify how to open settings for it. I'd like to change the default term to Kitty.

**Comment by alex1701c** [comment]
Please search for "Plasma Search" in Krunner, open the system settings entry and search for "tmux" in the search field.

**Comment by alex1701c** [comment]
Running `kcmshell5 plasmasearch --args tmuxrunner` in a terminal should also work

**Comment by octoshrimpy** [comment]
thank you!

I'll make a PR for readme with this info
