### ISSUE TITLE
custom terminal option not selectable

### ISSUE THREAD

**Issue by octoshrimpy** [alex1701c/TmuxRunner#3]
regardless of choice, the custom option remains greyed out and cannot be selected. 

I'd like to open it with Kitty, as that is my default-set terminal. 

another option would be to use the user defaults, as set in defaults or `$TERM`

![image](https://user-images.githubusercontent.com/7097172/200658497-b04188e0-1fba-40d9-8cd4-2b23f2160237.png)

**Comment by alex1701c** [comment]
Please check if filling in the fields and then selecting the option makes it work.

**Comment by alex1701c** [comment]
@octoshrimpy Does this work for you?
